#!/bin/bash

# add keys from mounted volume. check first
if [[ ! -d /wallet/keys ]]; then
	echo ERROR Expected gpg keys to be mounted to /wallet/keys, exiting
	exit 1
fi
if [[ `find /wallet/keys -type f | wc -l` -eq 0 ]]; then
	echo ERROR No keys found in mounted /wallet/keys, exiting
	exit 2
fi

# curl all  secrets we need. Must be present on $OBJECTS envvar.
for OBJECT in $OBJECTS; do
	echo Querying $OBJECT
	curl -s -k \
		--key /wallet/tls/Application1.key \
		--cert /wallet/tls/Application1.pem \
		"https://$WALLET_PORT_8443_TCP_ADDR:$WALLET_PORT_8443_TCP_PORT/$OBJECT" | \
	gpg -d -q --no-default-keyring \
		--secret-keyring /wallet/keys/*.sec \
		--keyring /wallet/keys/*.pub 2>/dev/null \
	>/tmp/$OBJECT

	# render config files. demo here: just show..
	ls -al /tmp/$OBJECT
	cat /tmp/$OBJECT
	# and remove
	rm /tmp/$OBJECTS
done

# exec "app", just shell for demoing
exec /bin/bash


